[Settings]
[build]
  publish = "dist"
  command = "npm run generate"
  functions = "functions/"

[context.branch-deploy]
  [context.production.environment]
    ORIGIN = "https://staging.grandgarage.eu"

[[redirects]]
  from = "/de/workshops/covid"
  to = "/de/covid"
  status = 301
