[Settings]
[build]
  publish = "dist"
  functions = "functions/"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

# Production context: all deploys from the Production branch
# set in your site’s Branches settings in the UI
# will inherit these settings.
[context.production]
  command = "yarn run generate"
[context.production.environment]
  NETLIFY_ENVIRONMENT = "production"

# Specific branch context: all deploys from
# this specific branch will inherit these settings.
[context.staging] # “staging” is a branch name
  command = "yarn run generate-staging && cp _branchdeploy_headers dist/_headers  && echo 'You are in STAGING context'"
[context.staging.environment]
  NETLIFY_ENVIRONMENT = "staging"

# Specific branch context: all deploys from
# this specific branch will inherit these settings.
[context.develop] # “develop” is a branch name
  command = "yarn run generate-develop && cp _branchdeploy_headers dist/_headers  && echo 'You are in DEVELOP context'"
[context.develop.environment]
  NETLIFY_ENVIRONMENT = "develop"
