[Settings]
[build]

# Production context: all deploys from the Production branch
# set in your site’s Branches settings in the UI
# will inherit these settings.
[context.production]
  publish = "dist"
  command = "npm run generate NUXT_ENV_DOMAIN=https://connector.grandgarage.eu"
  environment = { NUXT_ENV_API = "production", NUXT_ENV_DOMAIN = "https://connector.grandgarage.eu" }
  functions = "functions/"

# Specific branch context: all deploys from
# this specific branch will inherit these settings.
[context.staging] # “staging” is a branch name
  publish = "dist"
  command = "npm run generate NUXT_ENV_DOMAIN=https://staging-connector.in.grandgarage.eu"
  environment = { NUXT_ENV_API = "staging", NUXT_ENV_DOMAIN = "https://staging-connector.in.grandgarage.eu" }
  functions = "functions/"

[context.branch-deploy]
  [context.staging.environment]
    NUXT_ENV_DOMAIN = "https://staging-connector.in.grandgarage.eu"

# [[redirects]]
#   from = "/de/workshops/covid"
#   to = "/de/covid"
#   status = 301
