export const PACKAGES_SHORT_FORMS = {
  employee: 'MITARBEITER',
  smart_garage: 'SG',
  smart_garage_corporate: 'SG_CORP',
  digi: 'SG+DT',
  digi_corporate: 'SG+DT_CORP',
  grand: 'SG+ALL',
  grand_corporate: 'SG+ALL_CORP',
  grand_education: 'SG+ALL_EDU',
  grand_club: 'SG+ALL_VEREIN',
  metal: 'SG+MW',
  discount: 'DISCOUNT',
  credits_500: '500_CREDITS',
  credits_500_discounted: '500_CREDITS_DISCOUNTED',
};
